server:
    port: 8888
    servlet:
        context-path: /netactica
spring:
    datasource:
        data: classpath:/sql/paises.sql, classpath:/sql/ciudades.sql, classpath:/sql/vuelos.sql, classpath:/sql/pasajeros.sql
        driverClassName: org.h2.Driver
        password: password
        url: jdbc:h2:mem:testdb
        username: sa
    h2:
        console:
            enabled: true
            path: /h2-console
            settings:
                trace: false
                web-allow-others: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create